services:
    localstack:
        container_name: localstack_workshop
        image: localstack/localstack:latest
        ports:
            - "4566:4566" # LocalStack Gateway
            - "4510-4559:4510-4559" # External services port range
        environment:
            - SERVICES=ec2,s3,rds,iam,cloudwatch,logs,sts,lambda,apigateway
            - DEBUG=1
            - PERSISTENCE=0
            - LAMBDA_EXECUTOR=local
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=test
            - AWS_SECRET_ACCESS_KEY=test
        networks:
            - localstack-network

    atlantis:
        container_name: atlantis_workshop
        image: ghcr.io/runatlantis/atlantis:latest
        ports:
            - "4141:4141"
        env_file:
            - .env
        environment:
            # AWS/LocalStack Configuration - Override for container networking
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=test
            - AWS_SECRET_ACCESS_KEY=test
            - AWS_ENDPOINT_URL_EC2=http://localstack:4566
            - AWS_ENDPOINT_URL_S3=http://localstack:4566
            - AWS_ENDPOINT_URL_IAM=http://localstack:4566
            - AWS_ENDPOINT_URL_STS=http://localstack:4566
        volumes:
            - ./atlantis:/atlantis
            - ./terraform:/terraform
            - ./atlantis.yaml:/atlantis.yaml
            - ./policies:/policies
        depends_on:
            - localstack
        networks:
            - localstack-network

networks:
    localstack-network:
        driver: bridge
