# Allow all repositories to use custom workflows
repos:
- id: "/.*/.*" 
  allowed_overrides: [workflow, apply_requirements]
  allow_custom_workflows: true
- id: "github.com/Bright-04/terraform-atlantis-workshop"
  allowed_overrides: [workflow, apply_requirements]
  allow_custom_workflows: true
